camera_node:
  ros__parameters:
    camera_name: camera # camera unique name
    serial_no: '' # choose device by serial number
    usb_port_id: '' # choose device by usb port id
    device_type: '' # choose device by type
    config_file: '' # yaml config file
    unite_imu_method: 0 # [0-None, 1-copy, 2-linear_interpolation]
    json_file_path: '' # allows advanced configuration
    log_level: info # debug log level [DEBUG|INFO|WARN|ERROR|FATAL]
    output: screen # pipe node output [screen|log]
    depth_module.profile: 0,0,0 # depth module profile                           
    enable_depth: true # enable depth stream
    rgb_camera.profile: 0,0,0 # color image width
    enable_color: true # enable color stream
    enable_infra1: false # enable infra1 stream
    enable_infra2: false # enable infra2 stream
    infra_rgb: false # enable infra2 stream
    tracking_module.profile: 0,0,0 # fisheye width
    enable_fisheye1: true # enable fisheye1 stream
    enable_fisheye2: true # enable fisheye2 stream
    enable_confidence: true # enable depth stream
    gyro_fps: 0                           
    accel_fps: 0                           
    enable_gyro: false                          
    enable_accel: false                           
    enable_pose: true                           
    pose_fps: 200                           
    pointcloud.enable: false  
    pointcloud.stream_filter: 2 # texture stream for pointcloud
    pointcloud.stream_index_filter: 0 # texture stream index for pointcloud
    enable_sync: false                           
    align_depth.enable: false                           
    colorizer.enable: false
    clip_distance: -2.                           
    linear_accel_cov: 0.01                           
    initial_reset: false                           
    allow_no_texture_points: false                           
    ordered_pc: false
    calib_odom_file: ''
    topic_odom_in: '' # topic for T265 wheel odometry
    tf_publish_rate: 0.0 # Rate of publishing static_tf
    diagnostics_period: 0.0 # Rate of publishing diagnostics. 0=Disabled
    decimation_filter.enable: false # Rate of publishing static_tf
    rosbag_filename: '' # A realsense bagfile to run from as a device
    depth_module.exposure.1: 7500 # Initial value for hdr_merge filter
    depth_module.gain.1: 16 # Initial value for hdr_merge filter
    depth_module.exposure.2: 1 # Initial value for hdr_merge filter
    depth_module.gain.2: 16 # Initial value for hdr_merge filter
    wait_for_device_timeout: -1. # Timeout for waiting for device to connect (Seconds)
    reconnect_timeout: 6. # Timeout(seconds) between consequtive reconnection attempts
      